[package]
name = "qtcloud-learn-cli"
version = "0.0.1"
edition = "2021"
description = "量潮学习云的 CLI 工具"
license = "Apache-2.0"
repository = "https://github.com/quanttide/qtcloud-learn"

[[bin]]
name = "qtcloud-learn"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
